# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
  url: "https://peefy.github.io" 
# the base hostname & protocol for your site, e.g. http://example.com
baseurl: /
title: V
description: "V is my learning record."
keywords: 'jekyll,theme,gem-based,blog'
author:
  name: KAI
  job_title:
  location:
  email: xpf6677@163.com
  social_links:
    - name: facebook
      url:
    - name: github
      url: https://github.com/Peefy
    - name: instagram
      url:
    - name: linkedin
      url:
    - name: stackoverflow
      url:
    - name: twitter
      url: 
    - name: vk
      url:
home:
  section1: <h1>V</h1>
  section2: <h2>V is my learning record.</h2>
 #section3: <div class="social-links"><a class="ico-github btn" href="https://github.com/bryceyang/bryceyang.github.io" title="View on GitHub"></a></div>
blog:
  cc_license:  http://creativecommons.org/licenses/by-sa/4.0/
  cc_license_image: /assets/images/theme/cc-by-sa.png
  footer_content: V is my learning record.

disqus:
  shortname: bryceyang
  public_key: M1l4mNuPXdbLDtEyyCiWh6LN7HApjJEKtAtLStTeow2EGcPpw5dMpJMKe0sstvDO
google_analytics: 'UA-100095499-1'
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
